springfox:
  documentation:
    swagger:
      v2:
        path: /swagger.json

spring.datasource:
  driver-class-name: org.h2.Driver
  name:
  username:
  password:
  url: "jdbc:h2:mem:test;MODE=MySQL;IGNORECASE=TRUE;INIT=RUNSCRIPT FROM '~/create.sql';SCHEMA=public;"
  initialization-mode: never
  sql-script-encoding: UTF-8
  hikari:
    maximum-pool-size: 5
    minimum-idle: 2
    connection-init-sql: SELECT 1
    connection-test-query: SELECT 1
    connection-timeout: 1000
  type: com.zaxxer.hikari.HikariDataSource

